import './globals.css';

import type { Metadata } from 'next';
import { Geist_Mono, Figtree } from 'next/font/google';

import { ConvexClientProvider } from './ConvexClientProvider';
// import { authClient } from '../lib/auth-client';
// import { redirect } from 'next/navigation';

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { data: {user} } = authClie

  return (
    <html lang='en' className={figtree.variable}>
      <body className={`${geistMono.variable} antialiased`}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
